name: Node.JS CI/CD

on:
  push:
    branches: [main]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: NPM install, build and test
        run: |
          npm install
          npm test
        env:
          DB_URL: ${{ secrets.DB_URL }} 
          PORT: 3000
          JWT_SECRET_KEY : ${{ secrets.JWT_SECRET_KEY }} 
          JWT_EXPIRES : ${{ secrets.JWT_EXPIRES }} 
          SMPT_HOST: ${{ secrets.SMPT_HOST }} 
          SMPT_PORT: ${{ secrets.SMPT_PORT }} 
          SMPT_SERVICE: gmail
          SMPT_PASSWORD: ${{ secrets.SMPT_PASSWORD }} 
          SMPT_MAIL: ${{ secrets.SMPT_MAIL }} 
          ACTIVATION_SECRET: ${{ secrets.ACTIVATION_SECRET }} 

  deploy:
    name: Deploy
    needs: [test] 
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} 
          api-key: ${{ secrets.RENDER_API_KEY }} 