name: Node.JS CI/CD

on:
  push:
    branches: [main]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: NPM install, build and test
        run: |
          npm install
          npm test
        env:
          DB_URL: mongodb+srv://eric:francis1122@cluster1.kagkqfh.mongodb.net/?retryWrites=true&w=majority
          PORT: 7545
          JWT_SECRET_KEY : "2FtynxXT1NTf2K1Mo4i6AOvtdIPJKIRTY"
          JWT_EXPIRES : 2d
          SMPT_HOST: smtp.gmail.com
          SMPT_PORT: 465
          SMPT_SERVICE: gmail
          SMPT_PASSWORD: xksycvxukjntzucb
          SMPT_MAIL: nwaokefrancis@gmail.com
          ACTIVATION_SECRET:  'PWj0fI#&DsZY9w$8tHe11*yr9F45K*j2xj&fceGZ!tEnMNZcEN'



